---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: instance-centos7
    box: lpf/centos7docker
  - name: instance-ubuntu1804
    box: lpf/ubuntu1804docker
provisioner:
  name: ansible
