---
- when: dockerfile_builder_image is defined and dockerfile_builder_image
  block:
    - name: Log into registry
      when: dockerfile_builder_login | default(false)
      register: dockerfile_builder_login_state
      docker_login:
        username: "{{ dockerfile_builder_login.username }}"
        password: "{{ dockerfile_builder_login.password }}"
        email: "{{ dockerfile_builder_login.email | default(omit) }}"
        registry: "{{ dockerfile_builder_login.registry | default(omit) }}"
        reauthorize:
          "{{ dockerfile_builder_login.reauthorize | default(omit) }}"
        config_path:
          "{{ dockerfile_builder_login.config_path | default(omit) }}"

    - name: check builder directory
      file:
        dest: "{{ dockerfile_builder_dest }}"
        state: directory

    - name: copy image build directory
      copy:
        src: "{{ dockerfile_builder_image }}/"
        dest: "{{ dockerfile_builder_image_dest }}/"
        mode: preserve

    - name: create Dockerfile
      template:
        src: "{{ dockerfile_builder_image_template_src }}"
        dest: "{{ dockerfile_builder_image_template_dest }}"

    - name: build image
      docker_image:
        name: "{{ dockerfile_builder_image }}"
        build:
          path: "{{ dockerfile_builder_image_dest }}"
          pull: "{{ dockerfile_builder_image_pull | default(false) }}"
          arg: "{{ dockerfile_builder_image_args | default(omit) }}"
          dockerfile:
            "{{ dockerfile_builder_image_dockerfile | default(omit) }}"
        source: build
        push: "{{ dockerfile_builder_image_push | default(omit) }}"
        force_source:
          "{{ dockerfile_builder_force_source | default(false) }}"
        debug: "{{ dockerfile_builder_debug | default(omit) }}"

  always:
    - name: Log out
      when:
        dockerfile_builder_login_state is changed
      docker_login:
        registry: "{{ dockerfile_builder_login.registry | default(omit) }}"
        state: absent
