---
- when: dockerfile_builder_image is defined and dockerfile_builder_image
  block:
    - debug:
        msg: "building: {{ dockerfile_builder_image }}"

    - name: check image build directory
      register: dockerfile_builder_check_dir
      file:
        dest: "{{ dockerfile_builder_path }}"
        state: directory

    - name: create Dockerfile
      register: dockerfile_builder_create_dockerfile
      template:
        src: "{{ dockerfile_builder_template_src }}"
        dest: "{{ dockerfile_builder_template_dest }}"

    - name: sync image build directory
      register: dockerfile_builder_copy_build
      synchronize:
        src: "{{ dockerfile_builder_src }}/"
        dest: "{{ dockerfile_builder_path }}/"
        rsync_opts:
          - "--delete"
          - "--exclude=Dockerfile*"

    - name: force build
      when:
        dockerfile_builder_check_dir is changed or
        dockerfile_builder_copy_build is changed or
        dockerfile_builder_create_dockerfile is changed
      set_fact:
        dockerfile_builder_force_source: true

    - name: docker build
      include_tasks: docker.yml
      when: dockerfile_builder == 'docker'

    - name: podman build
      include_tasks: podman.yml
      when: dockerfile_builder == 'podman'
