---
- when: dockerfile_builder_image is defined and dockerfile_builder_image
  block:
    - debug:
        msg: "building: {{ dockerfile_builder_image }}"

    - name: check image build directory
      register: dockerfile_builder_check_dir
      file:
        dest: "{{ dockerfile_builder_path }}"
        state: directory

    - name: create Dockerfile
      when: dockerfile_builder_template_omit is not defined
      register: dockerfile_builder_create_dockerfile
      template:
        src: "{{ dockerfile_builder_template_src }}"
        dest: "{{ dockerfile_builder_template_dest }}"

    - name: sync image build directory
      when:
        - dockerfile_builder_src != dockerfile_builder_path
        - dockerfile_builder_src_omit is not defined
      register: dockerfile_builder_copy_build
      synchronize:
        src: "{{ dockerfile_builder_src }}/"
        dest: "{{ dockerfile_builder_path }}/"
        delete: true
        checksum: "{{ dockerfile_builder_sync_checksum | default(omit) }}"
        times: "{{ false if dockerfile_builder_sync_checksum |
          default(false) else omit }}"
        rsync_opts:
          - "--exclude=Dockerfile*"

    - when:
        - dockerfile_builder_build_omit_if_no_changes | default(false)
        - dockerfile_builder_copy_build is defined
        - dockerfile_builder_copy_build is not changed
      block:
        - name: omit build because there are no changes
          set_fact:
            dockerfile_builder_build_omit: true

    - name: force build
      when:
        dockerfile_builder_check_dir is changed or
        dockerfile_builder_copy_build is changed or
        dockerfile_builder_create_dockerfile is changed
      set_fact:
        dockerfile_builder_force_source: true

    - when: not dockerfile_builder_build_omit | default(false)
      block:
        - name: docker build
          include_tasks: docker.yml
          when: dockerfile_builder == 'docker'

        - name: podman build
          include_tasks: podman.yml
          when: dockerfile_builder == 'podman'
