---
- when: dockerfile_builder_image is defined and dockerfile_builder_image
  block:
    - name: Log into registry
      when: dockerfile_builder_login | default(false)
      register: dockerfile_builder_login_state
      docker_login:
        username: "{{ dockerfile_builder_login.username }}"
        password: "{{ dockerfile_builder_login.password }}"
        reauthorize:
          "{{ dockerfile_builder_login.reauthorize | default(omit) }}"
        config_path:
          "{{ dockerfile_builder_login.config_path | default(omit) }}"

    - name: check image build directory
      file:
        dest: "{{ dockerfile_builder_image_dest }}"
        state: directory

    - name: check if image conf directory exists
      stat:
        path: "{{ dockerfile_builder_image_conf }}"
      register: dockerfile_builder_image_conf_exists

    - name: copy conf directory
      when: dockerfile_builder_image_conf_exists.stat.exists
      register: copy_conf
      copy:
        src: "{{ dockerfile_builder_image_conf }}"
        dest: "{{ dockerfile_builder_image_dest }}"

    - name: create Dockerfile
      register: create_dockerfile
      template:
        src: "{{ dockerfile_builder_image_template_src }}"
        dest: "{{ dockerfile_builder_image_template_dest }}"

    - name: build image
      when:
        copy_conf is changed or
        create_dockerfile is changed or
        dockerfile_builder_force_source | default(false)
      docker_image:
        name: "{{ dockerfile_builder_image }}"
        build:
          path: "{{ dockerfile_builder_image_dest }}"
          pull: "{{ dockerfile_builder_image_pull | default(false) }}"
          arg: "{{ dockerfile_builder_image_args | default(omit) }}"
          dockerfile:
            "{{ dockerfile_builder_image_dockerfile | default(omit) }}"
        source: build
        push: "{{ dockerfile_builder_image_push | default(omit) }}"
        force_source:
          "{{ dockerfile_builder_force_source | default(false) }}"
        debug: "{{ dockerfile_builder_debug | default(omit) }}"

  always:
    - name: Log out
      when: dockerfile_builder_login_state is not skipped
      docker_login:
        state: absent
