---
dependency:
  name: galaxy
driver:
  name: docker
  # pull: no
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance_${MOLECULE_DISTRO:-centos7}
    image:
      "quay.io/jobcespedes/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
