---
- name: Prepare
  hosts: all
  tasks:
    - name: copy demo folder
      copy:
        src: example.com
        dest: ./

    - name: requirements
      block:
        - name: update cache
          when: ansible_os_family == 'Debian'
          apt:
            update_cache: true

        - name: pkgs
          package:
            name: rsync
